name: CI Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Node.js install 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Installing dependencies
        run: npm ci

      - name: Tests
        run: npm test

      - name: Build 
        run: npm run build
